<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2018
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * CustomElements Plugin
 */
$GLOBALS['TL_LANG']['PCT_CUSTOMELEMENTS']['PLUGINS']['ratings'][0] = 'Bewertungs Plugin';
$GLOBALS['TL_LANG']['PCT_CUSTOMELEMENTS']['PLUGINS']['ratings'][1] = 'Dieses Plugin erweitert das Basis-"Bewertungs"-Attribute (Bestandteil des CustomCatalog Paket), um die Speicherung und Auswertung abgegebener Bewertungen. Das Plugin stellt zusätzliche Filter für die Filterung nach Bewertungen und Sortierungen im Frontend bereit, sowie eine Übersicht im Backend.<br>Optional kann die Kommentar-Funktion je Bewertungs-Attribut aktiviert werden.';

/**
 * Texts
 */
$GLOBALS['TL_LANG']['MSC']['ratings_subject'] = 'Neue Bewertung auf %s';
$GLOBALS['TL_LANG']['MSC']['ratings_message'] = '
Eine neue Bewertung wurde hinterlassen.

Von: %s
Bewertung: %s
Ziel: %s
Eintrag: %s

Wenn Sie Bewertungen moderieren, müssen Sie sich im Backend anmelden und die Bewertung veröffentlichen.';
$GLOBALS['TL_LANG']['MSC']['ratings_emptyList'] = 'Keine Bewertungen vorhanden';
$GLOBALS['TL_LANG']['MSC']['ratings_helpful_label'] = 'Nützlich';
$GLOBALS['TL_LANG']['MSC']['ratings_not_helpful_label'] = 'Nicht nützlich';
$GLOBALS['TL_LANG']['MSC']['ratings_helpful'] = '%s Personen fanden diese Information hilfreich';
$GLOBALS['TL_LANG']['MSC']['ratings_helpful_single'] = '%s Person fand diese Information hilfreich';
$GLOBALS['TL_LANG']['MSC']['ratings_not_helpful'] = '%s Personen fanden diese Information nicht hilfreich';
$GLOBALS['TL_LANG']['MSC']['ratings_not_helpful_single'] = '%s Person fand diese Information nicht hilfreich';

/**
 * Filter labels
 */
$GLOBALS['TL_LANG']['MSC']['ratings_filter']['tstamp']['asc'] 		= 'Datum [aufsteigend]';
$GLOBALS['TL_LANG']['MSC']['ratings_filter']['tstamp']['desc'] 		= 'Datum [absteigen]';
$GLOBALS['TL_LANG']['MSC']['ratings_filter']['rating']['asc'] 		= 'Bewertung [aufsteigend]';
$GLOBALS['TL_LANG']['MSC']['ratings_filter']['rating']['desc'] 	= 'Bewertung [absteigen]';
$GLOBALS['TL_LANG']['MSC']['ratings_filter']['helpful']['asc'] 		= 'Nützlich [aufsteigend]';
$GLOBALS['TL_LANG']['MSC']['ratings_filter']['helpful']['desc'] 	= 'Nützlich [absteigen]';
$GLOBALS['TL_LANG']['MSC']['ratings_filter']['not_helpful']['asc'] 	= 'Nicht nützlich [aufsteigend]';
$GLOBALS['TL_LANG']['MSC']['ratings_filter']['not_helpful']['desc']	= 'Nicht nützlich [absteigen]';