<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2018
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * CustomElements Plugin
 */
$GLOBALS['TL_LANG']['PCT_CUSTOMELEMENTS']['PLUGINS']['ratings'][0] = 'Bewertungs Plugin';
$GLOBALS['TL_LANG']['PCT_CUSTOMELEMENTS']['PLUGINS']['ratings'][1] = 'Dieses Plugin erweitert das Basis-"Bewertungs"-Attribute (Bestandteil des CustomCatalog Paket), um die Speicherung und Auswertung abgegebener Bewertungen. Das Plugin stellt zusätzliche Filter für die Filterung nach Bewertungen und Sortierungen im Frontend bereit, sowie eine Übersicht im Backend.<br>Optional kann die Kommentar-Funktion je Bewertungs-Attribut aktiviert werden.';
