<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2018
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Filters
 */
$GLOBALS['TL_LANG']['PCT_CUSTOMELEMENTS']['FILTERS']['ratings'][0]				= 'Bewertungen';
$GLOBALS['TL_LANG']['PCT_CUSTOMELEMENTS']['FILTERS']['ratings'][1]				= 'Fügen Sie einen Filter hinzu, der nach abgegebenen Bewertungen filtert';
$GLOBALS['TL_LANG']['PCT_CUSTOMELEMENTS']['FILTERS']['ratings_sorting'][0]		= 'Bewertungen-Sortierung';
$GLOBALS['TL_LANG']['PCT_CUSTOMELEMENTS']['FILTERS']['ratings_sorting'][1]		= 'Fügen Sie einen Sortierungsfilter für Bewertungen hinzu.';