<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2018
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */


$GLOBALS['TL_LANG']['tl_module']['customcatalog_visibles_ratings'][0] = 'Attribut';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_visibles_ratings'][1] = 'Wählen Sie das Bewertungs-Attribut aus.';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_sortField_ratings']['rating'] = 'Bewertungswert [rating]';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_sortField_ratings']['helpful'] = 'Hilfreich [helpful]';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_sortField_ratings']['tstamp'] = 'Zeitstempel [tstamp]';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_sortField_ratings']['counter'] = 'Anzahl [counter]';