<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2014
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['min_value'][0] 			= 'Minimum, Untere Grenze';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['min_value'][1] 			= 'Geben Sie die untere Grenze des Filters ein.';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['max_value'][0] 			= 'Maximum, Obere Grenze';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['max_value'][1] 			= 'Geben Sie die obere Grenze des Filters ein.';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['steps_value'][0] 		= 'Schritte';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['steps_value'][1] 		= 'Geben Sie einen Wert für die Schritte ein, um die der Wert verändert wird.';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['range_mode'][0] 		= 'Filterbereich';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['range_mode'][1] 		= 'Wählen Sie die Bereichsgrenzen, wie der Filter angewendet werden soll. "Dazwischen" fügt die jquery UI Bibliothek der Seite hinzu.';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['range_mode']['ht'] 		= 'Größer [>]';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['range_mode']['hte'] 	= 'Größer-gleich [>=]';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['range_mode']['lt'] 		= 'Kleiner [<]';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['range_mode']['lte'] 	= 'Kleiner-gleich [<=]';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['range_mode']['between'] = 'Dazwischen';

$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['defaultMulti']['ratings_sorting'][0] = 'Sortierfelder';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['defaultMulti']['ratings_sorting'][1] = 'Wählen Sie die angezeigten Sortierfelder';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['defaultMulti']['ratings_sorting']['tstamp'] = 'Datum (absteigend und aufsteigend) [tstamp]';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['defaultMulti']['ratings_sorting']['rating'] = 'Bewertung (absteigend und aufsteigend) [rating]';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['defaultMulti']['ratings_sorting']['helpful'] = 'Nützlich (absteigend und aufsteigend) [helpful]';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['defaultMulti']['ratings_sorting']['not_helpful'] = 'Nicht nützlich (absteigend und aufsteigend) [not_helpful]';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['defaultMulti']['ratings_sorting']['count'] = 'Anzahl abgegebener Stimmen (absteigend und aufsteigend)';