<?php
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2018
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */


/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['ratings_legend'] 		= 'Bewertungs-Einstellungen';


/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['allowRatings'][0] 		= 'Bewertungen speichern';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['allowRatings'][1] 		= 'Die Bewertungen von Besuchern nachhaltig speichern.';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['ratings_notify'][0] 		= 'Benachrichtung an';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['ratings_notify'][1] 		= 'Bitte legen Sie fest, wer beim Hinzufügen neuer Bewertungen benachrichtigt wird.';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['ratings_moderate'][0] 	= 'Bewertungen moderieren';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['ratings_moderate'][1] 	= 'Bewertungen erst nach Bestätigung auf der Webseite veröffentlichen.';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['ratings_sortOrder'][0] 	= 'Sortierreihenfolge';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['ratings_sortOrder'][1] 	= 'Standardmäßig werden Bewertungen nach dem Zeitstempel aufsteigend sortiert.';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['ratings_sortOrder']['tstamp_asc'] 	= 'Datum aufsteigend';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['ratings_sortOrder']['tstamp_desc'] 	= 'Datum absteigend';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['ratings_sortOrder']['rating_asc'] 	= 'Bewertung aufsteigend';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['ratings_sortOrder']['rating_desc'] 	= 'Bewertung absteigend';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['ratings_perPage'][0] 	= 'Bewertungen pro Seite';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['ratings_perPage'][1] 	= 'Anzahl an Bewertungen pro Seite. Geben Sie 0 ein, um den automatischen Seitenumbruch zu deaktivieren.';

