<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2018
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Config Label
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_ratings']['config']['label'] 	= 'Bewertungen'; 

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_ratings']['source'][0]			= 'Ursprung';
$GLOBALS['TL_LANG']['tl_pct_customelement_ratings']['source'][1]			= 'Der Ursprung der Bewertung';
$GLOBALS['TL_LANG']['tl_pct_customelement_ratings']['tstamp'][0]			= 'Zeitstempel';
$GLOBALS['TL_LANG']['tl_pct_customelement_ratings']['tstamp'][1]			= 'Das Datum der Bewertung';
$GLOBALS['TL_LANG']['tl_pct_customelement_ratings']['published'][0]			= 'Veröffentlicht';
$GLOBALS['TL_LANG']['tl_pct_customelement_ratings']['published'][1]			= 'Bewertung ist veröffentlicht / unveröffentlicht';
$GLOBALS['TL_LANG']['tl_pct_customelement_ratings']['rating'][0]			= 'Wertung';
$GLOBALS['TL_LANG']['tl_pct_customelement_ratings']['rating'][1]			= 'Der Bewertungswert';
$GLOBALS['TL_LANG']['tl_pct_customelement_ratings']['helpful'][0]			= 'Hilfreich';
$GLOBALS['TL_LANG']['tl_pct_customelement_ratings']['helpful'][1]			= 'Bewertung ist hilfreich oder nicht.';
$GLOBALS['TL_LANG']['tl_pct_customelement_ratings']['attr_id'][0]			= 'Attribut';
$GLOBALS['TL_LANG']['tl_pct_customelement_ratings']['attr_id'][1]			= 'Das verknüpfte Bewertungs-Attribut.';
$GLOBALS['TL_LANG']['tl_pct_customelement_ratings']['comment'][0]			= 'Kommentar';
$GLOBALS['TL_LANG']['tl_pct_customelement_ratings']['comment'][1]			= 'Das verknüpfte Kommentar.';
$GLOBALS['TL_LANG']['tl_pct_customelement_ratings']['member'][0]			= 'Mitglied';
$GLOBALS['TL_LANG']['tl_pct_customelement_ratings']['member'][1]			= 'Die ID des Mitglieds, das die Bewertung abgegeben hat.';


/**
 * Buttons
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_ratings']['comment'][0]			= 'Kommentar bearbeiten';
$GLOBALS['TL_LANG']['tl_pct_customelement_ratings']['comment'][1]			= 'Kommentar ID %s bearbeiten';
$GLOBALS['TL_LANG']['tl_pct_customelement_ratings']['attribute'][0]			= 'Bewertungs-Attribut bearbeiten';
$GLOBALS['TL_LANG']['tl_pct_customelement_ratings']['attribute'][1]			= 'Das Bewertungs-Attribut bearbeiten';
$GLOBALS['TL_LANG']['tl_pct_customelement_ratings']['show'][0]				= 'Informationen zu Bewertung ID %s';
$GLOBALS['TL_LANG']['tl_pct_customelement_ratings']['show'][1]				= 'Informationen zu Bewertung ID %s anzeigen';
$GLOBALS['TL_LANG']['tl_pct_customelement_ratings']['toggle'][0]			= 'Bewertung veröffentlichen / unveröffentlichen';
$GLOBALS['TL_LANG']['tl_pct_customelement_ratings']['toggle'][1]			= 'Bewertungs ID %s veröffentlichen / unveröffentlichen';
